spring.application.name=clinica-api


#Configuração do Banco de Dados MySQL (XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3306/clinica-api
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mostra no console os comandos SQL executados pela aplica??o
spring.jpa.show-sql=true

# Formata o SQL exibido no console para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true